Gaia OS Plugin
CiscoTestAutomation/unicon.plugins pull request #19
Opened 2021-04-03 03:26 UTC by TestingBytes

This is the first release of a Gaia OS Unicon Plugin. This has been tested against physical and virtual Check Point firewalls for the last few weeks without issue, using the parsers in https://github.com/CiscoTestAutomation/genieparser/pull/408

Gaia Plugin includes:

- Mock Gaia Device and Test Data
- Test script
- Gaia Connection Provider
- Gaia State Machine (Note: Gaia OS supports an 'expert' mode that is not supported by this plugin at this time, but the plugin is still very useful in it's current state)
- Custom Traceroute Service

2021-04-06 01:49 UTC, tahigash requested changes
thank you for your contribution. reviewed and left comments.

2021-04-06 01:49 UTC, tahigash commented on src/unicon/plugins/gaia/patterns.py
> +        # [Expert@gw-a:0]#
we will see hostname in prompt? for this case, `gw-a` is hostname? we can use `%N` as placeholder for hostname. please check below iosxr code.
https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/iosxr/patterns.py#L11

2021-04-06 01:49 UTC, tahigash commented on src/unicon/plugins/gaia/__init__.py
> +        # super().__init__()
any reason why you need to comment this? I think still `send`/`sendline`/`transmit`/etc are usable even for `gaia`.

2021-04-06 01:49 UTC, tahigash commented on src/unicon/plugins/gaia/service_implementation.py
> +    def call_service(self, addr, **kwargs):
better to do same fashion with existing plugin. passing command, timeout, error_pattern, and also logging like `con.log.debug("+++ traceroute +++")
https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/generic/service_implementation.py#L1082

2021-04-06 01:49 UTC, tahigash commented on src/unicon/plugins/gaia/service_implementation.py
> +        self.timeout = 60*20
simply `120`

2021-04-06 01:49 UTC, tahigash commented on src/unicon/plugins/gaia/settings.py
> +        self.CONNECTION_TIMEOUT = 60*5
same. `120`

2021-04-06 01:49 UTC, tahigash commented on src/unicon/plugins/gaia/statemachine.py
> +        clish = State("enable", patterns.clish_prompt)
based on above comment, `clish` is not `enable`(=`expert`) mode? if so, better to have appropriate state name such as `clish` or `disable` (we use `disable` for non-enable mode in Unicon)

2021-04-06 11:38 UTC, dwapstra commented on src/unicon/plugins/gaia/patterns.py
> +        self.clish_prompt = r'.*> '
The prompt should follow best practice format and include `^(.*?)` at the start of the regex. The following looks more appropriate, assuming the hostname is `gw-a`:
```
^(.*?)%N>
```

2021-04-06 11:39 UTC, dwapstra commented on src/unicon/plugins/gaia/patterns.py
> +        self.expert_prompt = r'\[\w+\@.*\]\#'
The prompt should follow best practice format and include ^(.*?) at the start of the regex and end with `\s*$`

2021-04-06 11:40 UTC, dwapstra commented on src/unicon/plugins/gaia/service_implementation.py
> +                                r'connect: Invalid argument',
indentation is not aligned

2021-04-06 11:41 UTC, dwapstra commented on src/unicon/plugins/gaia/service_implementation.py
> +        try:
service implementation is done using an instance of the `Dialog` class and processing the dialog using `dialog.process` method, please see other plugins for reference.

2021-04-06 11:42 UTC, dwapstra commented on src/unicon/plugins/gaia/service_implementation.py
> +class GaiaTraceroute(BaseService):
there is a generic traceroute you can refer to as reference implementation https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/generic/service_implementation.py#L1059

2021-04-06 11:44 UTC, dwapstra commented on src/unicon/plugins/gaia/statemachine.py
> +        # Expert mode is not a currently supported state.
assuming expert mode is commonly used, should add the implementation for this as well.

2021-04-06 11:45 UTC, dwapstra commented on src/unicon/plugins/gaia/statements.py
> +'''
Do you really need specific implementation of the login and password statements?  If you can use the generic ones, best to re-use them.

2021-04-10 03:15 UTC, TestingBytes commented on src/unicon/plugins/gaia/patterns.py
> +        # [Expert@gw-a:0]#
Fixed - `%N` is now used in `clish_prompt` and `expert_prompt` patterns.

2021-04-10 03:19 UTC, TestingBytes commented on src/unicon/plugins/gaia/__init__.py
> +        # super().__init__()
You're correct - a number of the generic services do work, however some do not (i.e. reload, copy, etc.). I've uncommented that line so now all generic services are available. Would it make sense to create overloaded functions for all generic services and throw `NotImplementedException` for generic services that are not supported?

2021-04-10 03:23 UTC, TestingBytes commented on src/unicon/plugins/gaia/service_implementation.py
> +    def call_service(self, addr, **kwargs):
Thanks for the recommendation. I've refactored Traceroute to use the GenericTraceroute service so I think this is no longer relevant - the debug log output will occur when the generic implementation is called.

2021-04-10 03:23 UTC, TestingBytes commented on src/unicon/plugins/gaia/service_implementation.py
> +        self.timeout = 60*20
No longer relevant, but I have cleaned up all instances of these issues.

2021-04-10 03:24 UTC, TestingBytes commented on src/unicon/plugins/gaia/settings.py
> +        self.CONNECTION_TIMEOUT = 60*5
Fixed.

2021-04-10 03:25 UTC, TestingBytes commented on src/unicon/plugins/gaia/statemachine.py
> +        clish = State("enable", patterns.clish_prompt)
Thanks for feedback. Based on your and Dave's feedback I revisited this and the two Gaia CLI states 'clish' and 'expert' are now fully supported and named correctly.

2021-04-10 03:29 UTC, TestingBytes commented on src/unicon/plugins/gaia/patterns.py
> +        self.clish_prompt = r'.*> '
Thanks, I was unaware of this best practice. I have updated all patterns to use this style.

2021-04-10 03:30 UTC, TestingBytes commented on src/unicon/plugins/gaia/service_implementation.py
> +                                r'connect: Invalid argument',
Removed this code - no longer relevant.

2021-04-10 03:31 UTC, TestingBytes commented on src/unicon/plugins/gaia/service_implementation.py
> +        try:
Thanks for the feedback - I've refactored this to use the generic traceroute service.

2021-04-10 03:32 UTC, TestingBytes commented on src/unicon/plugins/gaia/service_implementation.py
> +class GaiaTraceroute(BaseService):
I found that I was able to fully use the generic traceroute service and am now using it as a base for the GaiaTraceroute service

2021-04-10 03:32 UTC, TestingBytes commented on src/unicon/plugins/gaia/statemachine.py
> +        # Expert mode is not a currently supported state.
expert mode is now fully supported

2021-04-10 03:33 UTC, TestingBytes commented on src/unicon/plugins/gaia/statements.py
> +'''
I reviewed this and you're correct, these were not needed. I've cleaned up unnecessary statements.

2021-04-10 03:34 UTC, TestingBytes commented on src/unicon/plugins/gaia/patterns.py
> +        self.expert_prompt = r'\[\w+\@.*\]\#'
Updated.

2021-04-22 02:12 UTC, tahigash approved these changes
thanks for addressing comments. approved with 1 small comment. Please quickly check and fix.

2021-04-24 03:55 UTC, TestingBytes commented on src/unicon/plugins/__init__.py
> +    'gaia'
Fixed

2021-04-28 07:15 UTC, dwapstra commented on src/unicon/plugins/gaia/__init__.py
> +            con.state_machine.paths[0].command = 'exit'
There should be no need to manipulate the statemachine paths like this. The state is determined by the prompt pattern and the transitions are defined in the statemachine to switch to other states.

Can you elaborate on the scenario that requires this logic?

2021-04-29 04:03 UTC, TestingBytes commented on src/unicon/plugins/gaia/__init__.py
> +            con.state_machine.paths[0].command = 'exit'
In Gaia OS a user can have their default shell configured to be either 'clish' or 'expert'. This was my attempt to make the transition commands dependent on that initial login state (which is correctly identified by the prompt). This is challenging because the clish/expert states in Gaia are not a true state machine - the way you transition between those states depends on the initial login state:

If the inital login state is 'clish', you use the command `expert` to move to expert, then use the command `exit` to leave expert and return to 'clish'. 

If the initial login state is 'expert', you use the command `clish` to move to clish, then use `exit` to leave clish and return to 'expert'

Example: If the user's default shell is set to 'clish', the prompt correctly identifies the state as 'clish' and the command to move to expert mode is 'expert'. Once in expert mode, to move back to clish you use the command 'exit' to leave 'expert' mode - you can't run the `clish` command from expert if expert was initiated from a 'clish' state. If you attempt to, you get the following error: 

```
# Login to Clish State
gw-a>
gw-a> expert 
Enter expert password:

# Expert State
[Expert@gw-a:0]# clish
CLINFR0479  You can't start interactive session from another interactive session
[Expert@gw-a:0]# exit    

# Clish State
gw-a>
```

The two options I can see to mange this are: 

1. Dynamically assign the Path commands based on initial state (there may be a better way to do this instead of manipulating the state_machine as part of the plugin init_handle - I'm open to suggestions here)
2. Use a Dialog to move between Expert and Clish: Assume the command 'clish' would move from expert to 'clish', and if the above error is observed, send the command 'exit' to move from expert to clish. I _think_ this could work, but it would need some testing. 

Does this make my intention more clear? Any suggestions on the best way to manage these transitions, given their dependencies on the initial login state?

2021-04-29 19:54 UTC, dwapstra commented on src/unicon/plugins/gaia/settings.py
> +        #self.ERROR_PATTERN = [r'*?Invalid command:\:*$']
Do you want to to add Gaia specific patterns? Otherwise you can remove this.

2021-05-08 03:33 UTC, TestingBytes commented on src/unicon/plugins/gaia/settings.py
> +        #self.ERROR_PATTERN = [r'*?Invalid command:\:*$']
Gaia specific patterns added.

2021-05-08 04:00 UTC, TestingBytes commented on src/unicon/plugins/gaia/__init__.py
> +            con.state_machine.paths[0].command = 'exit'
Updated the path commands using state_machine.get_path, as per your suggestion: 

```        if self.initial_state == 'expert':
            path = con.state_machine.get_path('clish','expert')
            path.command = 'exit'

            path = con.state_machine.get_path('expert','clish')
            path.command = 'clish'
```
https://github.com/CiscoTestAutomation/unicon.plugins/pull/19/files#diff-fc24035d766c9a3393b7c8b5704cd86821123dea8414f185b8c700eec2d5403fR40-R45

2021-05-11 07:29 UTC, dwapstra commented on src/unicon/plugins/gaia/settings.py
> +        print(f"init self.ERROR_PATTERN: {self.ERROR_PATTERN}")
Please remove this line

2021-05-11 07:33 UTC, dwapstra commented on src/unicon/plugins/tests/test_plugin_gaia.py
> +        self.assertIn("Product version", response)
one of the tests (e.g. this one) should check the response against the mock data for exact match. This is to confirm that prompt stripping is working. 

e.g.

    output = device.execute('show command')
    self.assertEqua(output, mock_data[state]['commands']['show command'])

2021-05-14 19:29 UTC, TestingBytes commented on src/unicon/plugins/gaia/settings.py
> +        print(f"init self.ERROR_PATTERN: {self.ERROR_PATTERN}")
Done

2021-05-14 20:15 UTC, TestingBytes commented on src/unicon/plugins/tests/test_plugin_gaia.py
> +        self.assertIn("Product version", response)
Done - Changed this to be an exact match between the execute() response and the mock data response. Test is passing.

2021-05-18 15:27 UTC, dwapstra approved these changes

2021-05-18 15:27 UTC, merged