Huawei Plugin implementation mibotiaf
CiscoTestAutomation/unicon.plugins pull request #26
Opened 2021-06-11 16:47 UTC by mibotiaf

This is a new plugin to connection for Huawei devices.

We included on "supported_os" the option "**hvrp**".  Also we created a new directory for this plugin named "hvrp". 

We used BaseSingleRpConnectionProvider, also the plugin was based on generic plugin.

**Miguel Botia**
mibotiaf@cisco.com

2021-06-15 09:03 UTC, dwapstra commented on src/unicon/plugins/hvrp/patterns.py
> +        self.config_prompt = r'^(.*)\[\~*\S+\]$'
As a best practice, end the pattern with `\s*$` to catch any white space that may be present

2021-06-15 09:04 UTC, dwapstra commented on src/unicon/plugins/hvrp/patterns.py
> +        self.commit_changes_prompt = r'Exit with uncommitted changes?'
the pattern should match the full statement and end with `\s*$` to make sure there is no match if this pattern is somewhere else in the buffer than the last line

2021-06-15 13:23 UTC, LukasMcClelland commented on src/unicon/plugins/hvrp/setting.py
> +        ]
Is there an exec command to standardize the screen width? Something like `screen-width 0 temporary`?

This would help to have the right text format during device output parsing

2021-07-30 13:46 UTC, LukasMcClelland commented
Hello @mibotiaf, are you planning on finishing this PR? If not, that's OK. We'll fix it up and merge it for you

2021-08-10 20:13 UTC, LukasMcClelland commented on src/unicon/plugins/hvrp/patterns.py
> +        self.config_prompt = r'^(.*)\[\~*\S+\]$'
Added

2021-08-10 20:13 UTC, LukasMcClelland commented on src/unicon/plugins/hvrp/patterns.py
> +        self.commit_changes_prompt = r'Exit with uncommitted changes?'
Added

2021-08-11 17:26 UTC, LukasMcClelland approved these changes

2021-08-21 15:06 UTC, tahigash requested changes

2021-08-21 15:06 UTC, tahigash commented on src/unicon/plugins/hvrp/statemachine.py
> +        config = State('config', patterns.config_prompt)
no non-enable mode?

2021-08-21 15:06 UTC, tahigash commented on src/unicon/plugins/hvrp/statemachine.py
> +"""
could you please add unittest like below?
https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/tests/test_plugin_dell.py

we don't have Hauwei device, so unittest is only way to validate if any is updated in this plugin.

2021-09-09 18:46 UTC, jeaubin commented
@mibotiaf So close to get this merged - Do you think you can help with the last round of comments and we will get it merged.

2021-10-19 22:44 UTC, LukasMcClelland commented
@jmdilly That would be excellent. Yes, unless I'm mistaken, the best course of action would be to fork @mibotiaf's [fork](https://github.com/mibotiaf/unicon.plugins) and continue working in the master branch. This way you have all of the work already completed and you also preserve the git commit history. Then a new PR can be opened

2021-11-22 14:23 UTC, nielsvanhooy commented on src/unicon/plugins/hvrp/patterns.py
>          # <HOSTNAME> #
i was also building a plugin for vrp and it seems to do the work.
however as soon as i test in our production environment (with hostnames for ex: one-gv-2595bk-04)
this would not work. needs a change to the regex)

        # <HOSTNAME-01> | <HOSTNAME>#
        self.enable_prompt = r'^(.*)\<.*\>'
        
         # [~HOSTNAME] | <HOSTNAME-01> #
        self.config_prompt = r'^(.*)\[.*\]'

2021-12-17 21:14 UTC, LukasMcClelland commented on src/unicon/plugins/hvrp/patterns.py
>          # <HOSTNAME> #
Hi Niels, thanks for weighing in! We're aiming to have this plugin added sometime soon, but we don't have access to Huawei devices. Would you be willing to add/update some of the code in this PR?

You can also send the device output to me and I can update it as well

2021-12-17 21:16 UTC, LukasMcClelland commented
@jmdilly Have you been able to make some progress on this since we last spoke? If so, can you share the fork you've been  working on?

2021-12-17 21:28 UTC, LukasMcClelland commented on src/unicon/plugins/hvrp/patterns.py
>          # <HOSTNAME> #
Nevermind, I just looked at [the fork you made](https://github.com/nielsvanhooy/unicon.plugins). Thanks for working on this!

2021-12-17 21:28 UTC, LukasMcClelland commented on src/unicon/plugins/hvrp/patterns.py
>          # <HOSTNAME> #
Let me know if you need help/guidance

2021-12-17 22:05 UTC, jmdilly commented
> @jmdilly Have you been able to make some progress on this since we last spoke? If so, can you share the fork you've been working on?

Hello! I have some unfinished work but as @nielsvanhooy proposed his fork before me, I stopped waiting this PR to be merged. I may propose some minor improvements later.

2021-12-20 15:49 UTC, LukasMcClelland commented
> Hello! I have some unfinished work but as @nielsvanhooy proposed his fork before me, I stopped waiting this PR to be merged. I may propose some minor improvements later.

Sounds good 👍

2021-12-30 16:19 UTC, nielsvanhooy commented
is there still some info needed from my side ( i made the other pull request: Huawei Plugin implementation mibotiaf. added tests/regex fixes).

let me know if you need anything :)

2022-01-11 15:59 UTC, merged