Enxr ssh
CiscoTestAutomation/unicon.plugins pull request #3
Opened 2020-11-10 09:34 UTC by ashojosh

Added EnXR support to PyATS

2020-11-10 22:31 UTC, LenzDong commented on src/unicon/plugins/iosxr/enxr/connection_provider.py
> +import pexpect
Could you please reuse the Spawn class in unicon
https://pubhub.devnetcloud.com/media/unicon/docs/developer_guide/eal.html#spawn
```
from unicon.eal.expect import Spawn

2020-11-10 22:59 UTC, LenzDong commented on src/unicon/plugins/iosxr/enxr/connection_provider.py
> +            log.error('EnXR connect failed ')
please use `self.connection.log`

2020-11-10 23:02 UTC, LenzDong commented on src/unicon/plugins/iosxr/enxr/service_implementation.py
> +    def connected(self):
this should be a `Connection` object attribute?

2020-11-10 23:04 UTC, LenzDong commented on src/unicon/plugins/iosxr/enxr/service_implementation.py
> +    def connect(self, **kwargs):
`connect()` function should be in connection provider, not inside service

2020-11-10 23:07 UTC, LenzDong commented on src/unicon/plugins/iosxr/enxr/connection_provider.py
> +class IOSXREnxrSingleRpConnectionProvider(IOSXRSingleRpConnectionProvider):
please refer to this guide line to implement new plugins:
https://pubhub.devnetcloud.com/media/unicon/docs/developer_guide/plugins.html#contribution

2020-11-10 23:11 UTC, LenzDong commented
Please add unit test for the new plugin

2020-11-30 12:39 UTC, ashojosh commented on src/unicon/plugins/iosxr/enxr/service_implementation.py
> +    def connect(self, **kwargs):
Done. 

I have basically referred connection_provider object here to get & use the spawn.

2020-11-30 12:39 UTC, ashojosh commented on src/unicon/plugins/iosxr/enxr/service_implementation.py
> +    def connected(self):
Sorry, I did not get it. I have implemented the BaseService class. Is there anything that  I am missing?

2020-11-30 12:39 UTC, ashojosh commented on src/unicon/plugins/iosxr/enxr/connection_provider.py
> +            log.error('EnXR connect failed ')
Done

2020-11-30 12:39 UTC, ashojosh commented on src/unicon/plugins/iosxr/enxr/connection_provider.py
> +import pexpect
using Spawn class is creating an issue in service_implementation. That's why I have used pexpect.spawn.

In the service implementation file, 'con.ssh.before' is giving an error that the Spawn class has no attribute before.

2020-11-30 12:41 UTC, ashojosh commented
Sorry for the delayed response to the pull request comments. My CEC ID had been locked because of some reason.

2020-12-07 22:23 UTC, miott commented
@LenzDong - Ashok has addressed review comments.  Can this pull request get merged or is there more he must do?

2020-12-07 23:38 UTC, simingy requested changes

2020-12-07 23:38 UTC, simingy commented on src/unicon/plugins/iosxr/enxr/connection_provider.py
> +import pexpect
then we should fix that issue. we are not going to start introducing another dependency (`pexpect`).

Please work with Lunzhi to have it resolved

2020-12-08 21:58 UTC, LenzDong commented on src/unicon/plugins/iosxr/enxr/connection_provider.py
> +import pexpect
Could you share what's the issue when using the Spawn class in unicon?

2020-12-11 18:02 UTC, LenzDong commented
As discussed, you can use the default iosxr plugin no need to create a new one for enxr

2020-12-11 18:02 UTC, closed without merging

2020-12-11 18:09 UTC, miott commented
> As discussed, you can use the default iosxr plugin no need to create a new one for enxr

Can you give an example of the device settings in the testbed file?  Not sure what you mean by "default".

2020-12-11 18:49 UTC, LenzDong commented
> > As discussed, you can use the default iosxr plugin no need to create a new one for enxr
> 
> Can you give an example of the device settings in the testbed file? Not sure what you mean by "default".

Here is an example testbed
```
devices:
    # WARNING: device name must match configured hostname
    bgl-ads-4861:
        type: iosxr
        os: iosxr   # <<< use the default iosxr plugin
        alias: uut
        credentials:
            default:
                username: admin
                password: admin
        connections:
            cli:
                class: unicon.Unicon
                command: exec   # <<< provide this to specify the spawn command instead of protocol and ip
```

2020-12-11 19:26 UTC, miott commented
> > > As discussed, you can use the default iosxr plugin no need to create a new one for enxr
> > 
> > 
> > Can you give an example of the device settings in the testbed file? Not sure what you mean by "default".
> 
> Here is an example testbed
> 
> ```
> devices:
>     # WARNING: device name must match configured hostname
>     bgl-ads-4861:
>         type: iosxr
>         os: iosxr   # <<< use the default iosxr plugin
>         alias: uut
>         credentials:
>             default:
>                 username: admin
>                 password: admin
>         connections:
>             cli:
>                 class: unicon.Unicon
>                 command: exec   # <<< provide this to specify the spawn command instead of protocol and ip
> ```

How do you use it? It does not have standard APIs like "configure" and "execute"
```
>>> dir(dev)
['CFG_TOPOLOGY_CLASS', 'ENTRY_POINT_NAME', '__class__', '__class__', '__contains__', '__delattr__', '__delattr__', '__device__', '__dict__', '__dict__', '__dir__', '__dir__', '__doc__', '__doc__', '__eq__', '__eq__', '__format__', '__format__', '__ge__', '__ge__', '__getattr__', '__getattr__', '__getattribute__', '__getattribute__', '__gt__', '__gt__', '__hash__', '__hash__', '__init__', '__init__', '__init_subclass__', '__init_subclass__', '__iter__', '__le__', '__le__', '__lt__', '__lt__', '__module__', '__module__', '__ne__', '__ne__', '__new__', '__new__', '__reduce__', '__reduce__', '__reduce_ex__', '__reduce_ex__', '__repr__', '__repr__', '__setattr__', '__setattr__', '__sizeof__', '__sizeof__', '__str__', '__str__', '__subclasshook__', '__subclasshook__', '__testbed__', '__weakref__', '__weakref__', '_default_connection_cls', '_deprecation_check', 'add_interface', 'alias', 'clean', 'connect', 'connectionmgr', 'connections', 'connections', 'credentials', 'custom', 'default_alias', 'default_connection_cls', 'destroy', 'destroy_all', 'device', 'disconnect', 'disconnect_all', 'find_links', 'instantiate', 'instantiate_pool', 'interfaces', 'is_connected', 'links', 'name', 'os', 'passwords', 'remote_devices', 'remote_interfaces', 'remove_interface', 'start_pool', 'tacacs', 'testbed', 'type']
>>> dev.type
'iosxr'
>>> dev.os
'iosxr'
>>>
```

2020-12-11 19:29 UTC, LenzDong commented
You will need to connect the device first
```
dev.connect(via='cli')