Add DellOS6 support
CiscoTestAutomation/unicon.plugins pull request #4
Opened 2020-12-18 02:45 UTC by DataKnox

Creating PR to add support for Dell PowerSwitch devices that run OS6 (a common OS on Dell PowerSwitch appliances). This has been tested on a Dell PowerSwitch N1548 switch and has no issues. 

(not sure whats up with the ACI/apic thing - looks like it is just spacing changes but no code was actually changed)

2020-12-18 16:03 UTC, tahigash reviewed
Please add Unittest for this plugin. Please refer to below `ios` example.
https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/tests/test_plugin_ios.py

2020-12-18 16:03 UTC, tahigash commented on src/unicon/plugins/dellos6/__init__.py
> +from unicon.plugins.ios.iosv import IosvSingleRpConnection
Is there any reason why you chose `IosvSingleRpConnection` class?

if no special reason, usually use `BaseSingleRpConnection` class. Here is reference code.
https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/ios/__init__.py#L2

2020-12-18 16:04 UTC, tahigash requested changes
thank you for your contribution! reviewed and left comments

2020-12-18 17:36 UTC, LenzDong commented on src/unicon/plugins/dellos6/services.py
> +from unicon.plugins.ios.iosv.service_implementation import Execute as IosvExec
any reason why need to use `iosv service_implementation`, usually we will use the generic one for new os:
https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/generic/service_implementation.py

2020-12-18 18:28 UTC, DataKnox commented on src/unicon/plugins/dellos6/services.py
> +from unicon.plugins.ios.iosv.service_implementation import Execute as IosvExec
Mostly because that is what is used as the example in the sample code given here **https://github.com/CiscoDevNet/pyats-plugin-examples/blob/master/unicon_plugin_example/src/unicon_plugin_example/services.py** , however I have tested changing it to the generic service_implementation and it works fine so I am happy to make that change if requested

2020-12-18 18:35 UTC, DataKnox commented on src/unicon/plugins/dellos6/__init__.py
> +from unicon.plugins.ios.iosv import IosvSingleRpConnection
You are correct. I was originally going to build off of IOSv since that is what is provided in the sample plugin, but I have re-built all the code locally to use Generic as well as renamed classes to be Dellos6Whatever and it is working fine on my side. Will add unit tests and resubmit PR

2020-12-18 19:01 UTC, LenzDong commented on src/unicon/plugins/dellos6/services.py
> +from unicon.plugins.ios.iosv.service_implementation import Execute as IosvExec
yea, please use generic one instead

2020-12-18 19:27 UTC, DataKnox commented on src/unicon/plugins/dellos6/services.py
> +from unicon.plugins.ios.iosv.service_implementation import Execute as IosvExec
Changed and re-requesting review

2020-12-18 22:05 UTC, DataKnox commented on src/unicon/plugins/dellos6/__init__.py
> +from unicon.plugins.ios.iosv import IosvSingleRpConnection
To confirm, I will also need to create a mock device and mock data?

2020-12-18 22:12 UTC, tahigash commented on src/unicon/plugins/dellos6/__init__.py
> +from unicon.plugins.ios.iosv import IosvSingleRpConnection
yes. that's correct.

2020-12-19 03:48 UTC, DataKnox commented on src/unicon/plugins/dellos6/__init__.py
> +from unicon.plugins.ios.iosv import IosvSingleRpConnection
Ok, I added unit tests (largely based off of the Junos unit tests). I didn't have much to go off of but I think they check out.

2020-12-19 13:33 UTC, tahigash commented on src/unicon/plugins/dellos6/__init__.py
> +class DellosSingleRPConnection(IosvSingleRpConnection):
confirmed the change

2020-12-19 14:50 UTC, tahigash commented on src/unicon/plugins/dellos6/__init__.py
> +from unicon.plugins.ios.iosv import IosvSingleRpConnection
thanks for adding UT. I saw some issues in UT. so I fixed via e4ff8d9.
Here is the test log after the fix.
```
python test_plugin_dellos6.py

2020-12-19 09:46:39,153: %UNICON-INFO: +++ DellOS6 logfile /tmp/DellOS6-20201219T094639152.log +++

2020-12-19 09:46:39,153: %UNICON-INFO: +++ Unicon plugin dellos6 +++
/Users/tahigash/.pyenv/versions/3.8.3/envs/pyats_dev_2101/pypi/unicon/src/unicon/bases/routers/connection.py:97: DeprecationWarning: Arguments 'username', 'enable_password','tacacs_password' and 'line_password' are now deprecated and replaced by 'credentials'.
  warnings.warn(message = "Arguments 'username', "
DellOS6#

2020-12-19 09:46:40,122: %UNICON-INFO: +++ connection to spawn: mock_device_cli --os dellos6 --state exec, id: 4453036720 +++

2020-12-19 09:46:40,122: %UNICON-INFO: connection to DellOS6

2020-12-19 09:46:40,176: %UNICON-INFO: +++ initializing handle +++
.
2020-12-19 09:46:40,179: %UNICON-INFO: +++ DellOS6 logfile /tmp/DellOS6-20201219T094640178.log +++

2020-12-19 09:46:40,179: %UNICON-INFO: +++ Unicon plugin dellos6 +++
DellOS6#

2020-12-19 09:46:41,131: %UNICON-INFO: +++ connection to spawn: mock_device_cli --os dellos6 --state exec, id: 4453263008 +++

2020-12-19 09:46:41,131: %UNICON-INFO: connection to DellOS6

2020-12-19 09:46:41,177: %UNICON-INFO: +++ initializing handle +++
.
2020-12-19 09:46:54,200: %UNICON-INFO: +++ DellOS6 logfile /tmp/DellOS6-20201219T094654199.log +++

2020-12-19 09:46:54,200: %UNICON-INFO: +++ Unicon plugin dellos6 +++
The authenticity of host '127.0.0.1 (127.0.0.1)' can't be established.
RSA key fingerprint is a1:07:ac:9b:8c:c2:db:c5:4c:dc:70:b5:09:2a:a5:b1.


2020-12-19 09:46:55,631: %UNICON-INFO: +++ connection to spawn: mock_device_cli --os dellos6 --state connect_ssh, id: 4453284208 +++

2020-12-19 09:46:55,632: %UNICON-INFO: connection to DellOS6
Are you sure you want to continue connecting (yes/no)? yes
User Access Verification
login: knox
Password: dell1111
DellOS6#

2020-12-19 09:46:56,580: %UNICON-INFO: +++ initializing handle +++
.
2020-12-19 09:46:56,585: %UNICON-INFO: +++ DellOS6 logfile /tmp/DellOS6-20201219T094656584.log +++

2020-12-19 09:46:56,585: %UNICON-INFO: +++ Unicon plugin dellos6 +++
DellOS6#

2020-12-19 09:46:57,554: %UNICON-INFO: +++ connection to spawn: mock_device_cli --os dellos6 --state exec, id: 4453419424 +++

2020-12-19 09:46:57,555: %UNICON-INFO: connection to DellOS6

2020-12-19 09:46:57,598: %UNICON-INFO: +++ initializing handle +++

2020-12-19 09:46:57,599: %UNICON-INFO: +++ DellOS6: executing command 'show ip interface' +++
show ip interface
"Default Gateway................................ 0.0.0.0
L3 MAC Address................................. F8B1.5683.8734

Routing Interfaces:

Interface    State   IP Address      IP Mask         Method
----------   -----   --------------- --------------- -------
Vl1          Down    0.0.0.0         0.0.0.0         DHCP
Vl20         Up      10.10.21.70     255.255.255.0   DHCP"
DellOS6#
.
----------------------------------------------------------------------
Ran 4 tests in 18.693s

OK

2020-12-19 14:51 UTC, tahigash approved these changes
for me, it looks good now. Please merge after having @LenzDong 's approval.

2020-12-19 16:48 UTC, LenzDong approved these changes

2020-12-19 16:49 UTC, merged