Huawei Plugin implementation mibotiaf. added tests/regex fixes
CiscoTestAutomation/unicon.plugins pull request #43
Opened 2021-11-23 10:12 UTC by nielsvanhooy

expanded upon "Huawei Plugin implementation mibotiaf "

fixed regexes for cases where the hostname can be like "zzz-ab-9999-ax-99" matches other variants to.
looked at unittests implementation from other OS'es and added for hvrp.

i tested this in our production environment and all seems to be well :)
also handled dialog [yes/no]  (in case you want to reboot/save configuration)

2021-11-23 16:10 UTC, domachad requested changes
Hi @nielsvanhooy, thank you for your contribution!

There are just a few details you need to adjust. I left some comments below.

Thanks once again!

2021-11-23 16:25 UTC, nielsvanhooy commented on docs/changelog/undistributed/template.rst
>  Templates
done. not sure what happened here or why that changed

2021-11-23 16:25 UTC, nielsvanhooy commented on src/unicon/plugins/hvrp/setting.py
> +"""
removed.

2021-11-23 16:26 UTC, nielsvanhooy commented on src/unicon/plugins/hvrp/setting.py
> +        self.CONSOLE_TIMEOUT = 60
we did not find any issues with leaving this out in the settings.py file.
i can report back to this tomorrow.

2021-11-23 18:36 UTC, d-the-iii requested changes
Thanks for your contribution. I just need you to take a look at the template file again and make it so you're not changing it and everything should be good.

2021-11-23 18:36 UTC, d-the-iii commented on docs/changelog/undistributed/template.rst
>  Templates
I'm looking at the pr and I still see it as making changes to the template file. I recommend having git checkout the version of the file in dev, I think that should fix it.

2021-11-23 20:41 UTC, nielsvanhooy commented on docs/changelog/undistributed/template.rst
>  Templates
took some time to get that fixed up. but it should be ok now. i see the changed files dropped from 14 to 13 :)

2021-11-23 21:18 UTC, domachad approved these changes

2021-11-24 16:26 UTC, d-the-iii approved these changes

2022-01-11 15:59 UTC, merged