add dell OS10 series support
CiscoTestAutomation/unicon.plugins pull request #7
Opened 2020-12-23 16:25 UTC by DataKnox

Added Dell OS10 series support. Confirmed tests against OS10 virtual appliance. Parser and tests included in already existing parser PR

2021-01-04 22:32 UTC, LenzDong commented on src/unicon/plugins/dell/os10/statemachine.py
> +class Dellos10SingleRpStateMachine(GenericSingleRpStateMachine):
Seems this class is same with this one, maybe you can inherit from this and no need to write duplicated code
https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/dell/statemachine.py

something like this
```
from unicon.plugins.dell.statemachine import DellSingleRpStateMachine

class Dellos10SingleRpStateMachine(DellSingleRpStateMachine):
    pass

2021-01-04 22:37 UTC, LenzDong commented on src/unicon/plugins/dell/os10/statements.py
> +'''
Same for this file, please reuse the code in this parent file if no difference
https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/dell/statements.py

2021-01-04 22:38 UTC, LenzDong commented on src/unicon/plugins/dell/os10/settings.py
> +'''
Settings can be reused as well:
https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/dell/settings.py

2021-01-04 22:40 UTC, LenzDong commented on src/unicon/plugins/dell/os10/patterns.py
> +'''
Please reuse the patterns in this file:
https://github.com/CiscoTestAutomation/unicon.plugins/blob/master/src/unicon/plugins/dell/patterns.py

2021-01-21 19:09 UTC, jeaubin commented
Hi @DataKnox 

we have an upcoming release next Wednesday. If you want to be part of this release, we would need comments to be addressed.

Otherwise, no problem, it can be part of the Feb release (Last Tuesday of every month)

2021-01-28 20:09 UTC, dwapstra commented
@DataKnox  please let us know if you need help updating the plugin.

2021-01-31 18:09 UTC, DataKnox commented
Hey y'all - I'm on paternity leave for next couple months and not actively working. Sorry to clog up the pipeline 😕

2021-01-31 18:40 UTC, tahigash commented
> Hey y'all - I'm on paternity leave for next couple months and not actively working. Sorry to clog up the pipeline 😕

Hi @DataKnox congrats and enjoy the paternity leave! We will see if we can update on behalf of you!

2021-08-21 15:08 UTC, tahigash commented
reassigned from @dwapstra to @LukasMcClelland . @LukasMcClelland please finish this up when you have a time.

2021-12-20 18:10 UTC, LukasMcClelland commented
Hey @DataKnox! I was thinking of making some changes to this PR and fixing up the unit tests so they pass. Would that be alright with you?

2022-01-11 16:12 UTC, LukasMcClelland approved these changes

2022-01-13 01:44 UTC, tahigash requested changes

2022-01-13 01:44 UTC, tahigash commented on src/unicon/plugins/dell/os10/__init__.py
> +    platform = 'os10'
@LukasMcClelland sorry, just remembered below discussion in parser.
https://github.com/CiscoTestAutomation/genieparser/pull/366#pullrequestreview-570117821

We decided to use only os `dnos10` instead of `os:dell / platformos10` before. Could you please update accordingly?

and please update below doc page as well.
https://pubhub.devnetcloud.com/media/unicon/docs/user_guide/supported_platforms.html

2022-02-28 23:40 UTC, tahigash approved these changes

2022-03-01 00:28 UTC, merged