Add Brocade Ironware Support
CiscoTestAutomation/unicon.plugins pull request #8
Opened 2020-12-28 11:01 UTC by jamesditrapani

### Description
Unicon Plugin created to handle connection(s) to Brocade devices running the Ironware NOS. Parsers are currently being written and a PR will be submitted in the Genie repo shortly. 

### Summary
- [x] - SingleRPHandler defined
- [x] - Custom ServiceList defined
- [x] - Ironware specific patterns defined
- [x] - Custom Service created (mpls_ping)
- [x] - Settings defined/overwritten
- [x] - State Machine created
- [x] - Mock data defined
- [x] - Mock device created
- [x] - Unittests created & passing (incl. custom service)
- [x] - Within PEP8 guidelines (somewhat)

### Testing
This plugin has been tested against the following software & hardware:
- Brocade MLX-8 - Ironware Version 5.8.0
- Brocade CES - Ironware Version 6.0.0

### Unittest results:
```
(pyats-env) [james.ditrapani@utils1][~/project_folder/pyats-dev/unicon.plugins/tests]
$ python test_plugin_ironware.py

2020-12-28 20:46:20,233: %UNICON-INFO: +++ mlx8 logfile /tmp/mlx8-20201228T204620232.log +++

2020-12-28 20:46:20,233: %UNICON-INFO: +++ Unicon plugin ironware +++
mlx8#

2020-12-28 20:46:20,815: %UNICON-INFO: +++ connection to spawn: mock_device_cli --os ironware --state exec, id: 140092574107128 +++

2020-12-28 20:46:20,815: %UNICON-INFO: connection to mlx8

2020-12-28 20:46:20,863: %UNICON-INFO: +++ initializing handle +++

2020-12-28 20:46:20,864: %UNICON-INFO: +++ mlx8: executing command 'terminal length 0' +++
terminal length 0
mlx8#
.test_plugin_ironware.py:76: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/mlx8-20201228T204620232.log' mode='a' encoding='UTF-8'>
  connect_reply=Dialog([[r'^(.*?)Password:']]))
ResourceWarning: Enable tracemalloc to get the object allocation traceback

2020-12-28 20:46:20,943: %UNICON-INFO: +++ mlx8 logfile /tmp/mlx8-20201228T204620941.log +++

2020-12-28 20:46:20,944: %UNICON-INFO: +++ Unicon plugin ironware +++
mlx8#

2020-12-28 20:46:21,522: %UNICON-INFO: +++ connection to spawn: mock_device_cli --os ironware --state exec, id: 140092573819736 +++

2020-12-28 20:46:21,523: %UNICON-INFO: connection to mlx8

2020-12-28 20:46:21,566: %UNICON-INFO: +++ initializing handle +++

2020-12-28 20:46:21,566: %UNICON-INFO: +++ mlx8: executing command 'terminal length 0' +++
terminal length 0
mlx8#
.
2020-12-28 20:46:34,681: %UNICON-INFO: +++ mlx8 logfile /tmp/mlx8-20201228T204634681.log +++

2020-12-28 20:46:34,682: %UNICON-INFO: +++ Unicon plugin ironware +++
The authenticity of host '127.0.0.1 (127.0.0.1)' can't be established.
RSA key fingerprint is xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.
Are you sure you want to continue connecting (yes/no)?

2020-12-28 20:46:35,357: %UNICON-INFO: +++ connection to spawn: mock_device_cli --os ironware --state connect_ssh, id: 140092573908832 +++

2020-12-28 20:46:35,358: %UNICON-INFO: connection to mlx8
yes
Username: ironware1
Password: pyatsRocks!
mlx8#

2020-12-28 20:46:35,505: %UNICON-INFO: +++ initializing handle +++

2020-12-28 20:46:35,506: %UNICON-INFO: +++ mlx8: executing command 'terminal length 0' +++
terminal length 0
mlx8#
.
2020-12-28 20:46:35,580: %UNICON-INFO: +++ mlx8 logfile /tmp/mlx8-20201228T204635579.log +++

2020-12-28 20:46:35,580: %UNICON-INFO: +++ Unicon plugin ironware +++
mlx8#

2020-12-28 20:46:36,301: %UNICON-INFO: +++ connection to spawn: mock_device_cli --os ironware --state exec, id: 140092573506416 +++

2020-12-28 20:46:36,301: %UNICON-INFO: connection to mlx8

2020-12-28 20:46:36,344: %UNICON-INFO: +++ initializing handle +++

2020-12-28 20:46:36,345: %UNICON-INFO: +++ mlx8: executing command 'show ip route' +++
show ip route
"Total number of IP routes: 449
Type Codes - B:BGP D:Connected I:ISIS O:OSPF R:RIP S:Static; Cost - Dist/Metric
BGP  Codes - i:iBGP e:eBGP
ISIS Codes - L1:Level-1 L2:Level-2
OSPF Codes - i:Inter Area 1:External Type 1 2:External Type 2 s:Sham Link
STATIC Codes - d:DHCPv6
        Destination        Gateway         Port           Cost          Type Uptime src-vrf
1       10.200.0.12/30     10.254.248.10   eth 2/2        110/28        O    40d0h  -
2       10.200.0.16/30     10.254.248.10   eth 2/2        110/194       O    6d12h  -
3       10.200.0.28/30     10.254.248.10   eth 2/2        110/138       O    40d0h  -
4       10.200.0.32/30     10.254.248.10   eth 2/2        110/36        O    40d0h  -
5       10.200.0.56/30     10.254.248.10   eth 2/2        110/36        O    12d4h  -
6       10.200.0.60/30     10.254.248.10   eth 2/2        110/38        O    40d0h  -
7       10.200.0.65/32     10.254.248.10   eth 2/2        110/63        O    40d0h  -
8       10.200.0.73/32     10.254.248.10   eth 2/2        110/73        O    40d0h  -
9       10.200.0.80/30     10.254.248.10   eth 2/2        110/76        O    1d1h   -
10      10.200.0.85/32     10.254.248.10   eth 2/2        110/27        O    40d0h  -
11      10.200.0.96/30     10.254.248.10   eth 2/2        110/36        O    40d0h  -
12      10.200.0.112/31    10.254.248.10   eth 2/2        110/36        O    40d0h  -
13      10.200.0.132/30    10.254.248.10   eth 2/2        110/129       O    30d20h -
14      10.200.0.140/30    10.254.248.10   eth 2/2        110/36        O    40d0h  -
15      10.200.0.148/30    10.254.248.10   eth 2/2        110/72        O    40d0h  -
16      10.200.0.152/30    10.254.248.10   eth 2/2        110/36        O    40d0h  -
17      10.200.0.158/32    10.254.248.10   eth 2/2        110/20        O2   12d9h  -
18      10.200.0.172/30    10.254.248.10   eth 2/2        110/39        O    40d0h  -
19      10.200.0.180/30    10.254.248.10   eth 2/2        110/39        O    40d0h  -
20      10.200.0.185/32    10.254.248.10   eth 2/2        110/29        O    40d0h  -
21      10.200.0.190/32    10.254.248.10   eth 2/2        110/39        O    40d0h  -
22      10.200.0.191/32    10.254.248.10   eth 2/2        110/73        O    40d0h  -
23      10.200.0.192/32    10.254.248.10   eth 2/2        110/37        O    40d0h  -
24      10.200.0.193/32    10.254.248.10   eth 2/2        110/129       O    6d12h  -
25      10.200.0.194/32    10.254.248.10   eth 2/2        110/37        O    40d0h  -
26      10.200.0.196/30    10.254.248.10   eth 2/2        110/76        O    40d0h  -
27      10.200.0.204/30    10.254.248.10   eth 2/2        110/128       O    40d0h  -
28      10.200.0.216/31    10.254.248.10   eth 2/2        110/39        O    40d0h  -
29      1.1.1.1/32  10.254.251.2    eth 5/1       110/42        O    15h47m -
        1.1.1.1/32  10.254.251.108  eth 7/1       110/42        O    15h47m -"
mlx8#
.
2020-12-28 20:46:36,420: %UNICON-INFO: +++ mlx8 logfile /tmp/mlx8-20201228T204636419.log +++

2020-12-28 20:46:36,420: %UNICON-INFO: +++ Unicon plugin ironware +++

2020-12-28 20:46:36,422: %UNICON-INFO: +++ mlx8: mpls_ping +++
mlx8#

2020-12-28 20:46:37,026: %UNICON-INFO: +++ connection to spawn: mock_device_cli --os ironware --state exec, id: 140092573549064 +++

2020-12-28 20:46:37,026: %UNICON-INFO: connection to mlx8

2020-12-28 20:46:37,069: %UNICON-INFO: +++ initializing handle +++

2020-12-28 20:46:37,069: %UNICON-INFO: +++ mlx8: executing command 'terminal length 0' +++
terminal length 0
mlx8#
ping mpls rsvp lsp mlx8.1_to_mlx8.4
Ping fails: LSP is down
mlx8#
.
2020-12-28 20:46:37,146: %UNICON-INFO: +++ mlx8 logfile /tmp/mlx8-20201228T204637145.log +++

2020-12-28 20:46:37,146: %UNICON-INFO: +++ Unicon plugin ironware +++

2020-12-28 20:46:37,148: %UNICON-INFO: +++ mlx8: mpls_ping +++
mlx8#

2020-12-28 20:46:37,745: %UNICON-INFO: +++ connection to spawn: mock_device_cli --os ironware --state exec, id: 140092573620768 +++

2020-12-28 20:46:37,745: %UNICON-INFO: connection to mlx8

2020-12-28 20:46:37,787: %UNICON-INFO: +++ initializing handle +++

2020-12-28 20:46:37,789: %UNICON-INFO: +++ mlx8: executing command 'terminal length 0' +++
terminal length 0
mlx8#
ping mpls rsvp lsp mlx8.1_to_ces.2
Send 5 96-byte MPLS Echo Requests over RSVP LSP mlx8.1_to_ces.2, timeout 5000 msec
Type Control-c to abort
!!!!!
Success rate is 100 percent (5/5),  [...]

2021-01-06 15:31 UTC, LenzDong commented on src/unicon/plugins/ironware/service_implementation.py
> +        self.error_pattern = [
it's better to put this into settings

2021-01-07 12:16 UTC, jamesditrapani commented on src/unicon/plugins/ironware/service_implementation.py
> +        self.error_pattern = [
@LenzDong Sorry, specifically what is better to be in the settings?

2021-01-07 15:14 UTC, LenzDong commented on src/unicon/plugins/ironware/service_implementation.py
> +        self.error_pattern = [
If this is a generic error pattern, you can put it in the settings
```
# inside src/unicon/plugins/ironware/settings.py 
self.ERROR_PATTERN=['Ping fails: LSP is down']

# in this script
self.error_pattern = connection.settings.ERROR_PATTERN
```

If it's just service specific error pattern, then you can just keep it here.

2021-01-07 15:23 UTC, LenzDong commented on src/unicon/plugins/ironware/statements.py
> +statements = GenericStatements()
Seems this variable is not used, please remove it

2021-01-07 23:50 UTC, jamesditrapani commented on src/unicon/plugins/ironware/service_implementation.py
> +        self.error_pattern = [
@LenzDong This is a service specific error pattern, will keep this in place.

2021-01-08 14:44 UTC, LenzDong approved these changes

2021-01-11 19:10 UTC, dwapstra requested changes
Please review the re-use of the generic statemachine as much as possible so minimize duplication of code.  The prompt patterns should be updated per best practice and the example mock does not match the prompt patterns defined?

2021-01-11 19:10 UTC, dwapstra commented on src/unicon/plugins/ironware/statemachine.py
> +        disable_to_enable = Path(disable,
You can re-use the generic implementation, as it already supports the 'enable' credential, no need to overwrite this Path.

I think you can just remove the rommon state and paths and re-use  the generic statemachine.

2021-01-11 19:10 UTC, dwapstra commented on src/unicon/plugins/ironware/statements.py
> +enable_stmt = Statement(pattern=patterns.disable_mode,
You don't need this, the statemachine will handle this for you.

2021-01-11 19:10 UTC, dwapstra commented on src/unicon/plugins/ironware/statements.py
> +def send_enabler(spawn, context, session):
This is not needed as the generic statemachine takes care of this.

2021-01-11 19:10 UTC, dwapstra commented on src/unicon/plugins/ironware/statements.py
> +def get_enable_credential_password(context):
If you would need to use this, you can use import directly from the generic statements.py, no need to redefine.

2021-01-11 19:10 UTC, dwapstra commented on src/unicon/plugins/ironware/statements.py
> +def enable_password_handler(spawn, context, session):
No need to redefine, you could import if you need it from generic statements.py

2021-01-11 19:10 UTC, dwapstra commented on src/unicon/plugins/ironware/statements.py
> +def login_handler(spawn, context, session):
By using the generic statemachine, you should not need this.

2021-01-11 19:10 UTC, dwapstra commented on src/unicon/plugins/ironware/statements.py
> +login_stmt = Statement(pattern=patterns.login_prompt,
By using the generic statemachine, you should not need this.

2021-01-11 19:10 UTC, dwapstra commented on src/unicon/plugins/ironware/statements.py
> +password_stmt = Statement(pattern=patterns.password,
By using the generic statemachine, you should not need this.

2021-01-11 19:10 UTC, dwapstra commented on src/unicon/plugins/ironware/patterns.py
> +        self.login_prompt = r' *Username: *?'
If you use the generic statemachine, the existing self.username and self.password patterns are used and you don't need these.

2021-01-11 19:10 UTC, dwapstra commented on src/unicon/plugins/ironware/patterns.py
> +        self.disable_mode = r'\w+@\w+>$'
As a best practice, patterns should start with this `^(.*?)`, this speeds up the matching and you can use the prompt stripping method to remove the prompt from the output.

2021-01-11 19:10 UTC, dwapstra commented on src/unicon/plugins/ironware/patterns.py
> +        self.privileged_mode = r'\w+@\w+#$'
As a best practice, using `\w` should usually be done with `[-\w]` since hostnames or usernames may contain `-` signs.

2021-01-11 19:10 UTC, dwapstra commented on src/unicon/plugins/ironware/service_implementation.py
> +        if self.result.rfind(self.connection.hostname):
If you use the pattern bestpractices with `^(.*?)` you should  be able to re-use the generic prompt stripping like this:
```
            if self.result:
                output = self.utils.truncate_trailing_prompt(
                    sm.get_state(sm.current_state),
                    self.result,
                    hostname=con.hostname,
                    result_match=dialog_match,
                )
```

2021-01-11 19:10 UTC, dwapstra commented on src/unicon/plugins/tests/mock_data/ironware/ironware_mock_data.yaml
> +  prompt: "mlx8#"
The prompt here does not match the patterns defined for the statemachine...?

2021-01-12 00:17 UTC, jamesditrapani commented on src/unicon/plugins/ironware/service_implementation.py
> +        if self.result.rfind(self.connection.hostname):
@dwapstra That worked perfectly, have utilised `truncate_trailing_prompt` in the newest commit.

2021-01-12 00:17 UTC, jamesditrapani commented on src/unicon/plugins/ironware/patterns.py
> +        self.privileged_mode = r'\w+@\w+#$'
@dwapstra Updated in latest commit, have also ensured we account for `.` along with `-`.

2021-01-12 00:18 UTC, jamesditrapani commented on src/unicon/plugins/ironware/patterns.py
> +        self.disable_mode = r'\w+@\w+>$'
@dwapstra Noted, updated in last commit.

2021-01-12 00:18 UTC, jamesditrapani commented on src/unicon/plugins/ironware/patterns.py
> +        self.login_prompt = r' *Username: *?'
@dwapstra Removed in latest commit.

2021-01-12 00:19 UTC, jamesditrapani commented on src/unicon/plugins/ironware/statements.py
> +enable_stmt = Statement(pattern=patterns.disable_mode,
@dwapstra `ironware.statements` has been removed in the latest commit. We should be okay to inherit from the generic.

2021-01-12 00:20 UTC, jamesditrapani commented on src/unicon/plugins/ironware/statemachine.py
> +        disable_to_enable = Path(disable,
@dwapstra Removed un-needed Path & State declarations, going to rely on `generic.statemachine`.

2021-01-12 14:09 UTC, dwapstra commented on src/unicon/plugins/ironware/patterns.py
> +        self.disable_mode = r'^(.*?)[-.\w]+@[-.\w]+>$'
If you want to add `.` to the pattern, you will need to escape it `\.` unless its a wildcard

2021-01-12 14:12 UTC, dwapstra commented on src/unicon/plugins/ironware/statemachine.py
> +        super().create()
@jamesditrapani  probably you want to do this:

```
from .patterns import IronWarePatterns
patterns = IronWarePatterns()

def create():
    enable = self.get_state('enable')
    enable.pattern = patterns.privileged_mode

    disable = self.get_state('disable')
    disable.pattern = patterns.disable_mode

    config = self.get_state('config')
    config.pattern = patterns.config_mode
```

2021-01-12 14:13 UTC, dwapstra commented on src/unicon/plugins/tests/test_plugin_ironware.py
> +class TestIronWarePluginConnect(unittest.TestCase):
Recommend to add decorators to reduce disconnect time:
```
@patch.object(unicon.settings.Settings, 'POST_DISCONNECT_WAIT_SEC', 0)
@patch.object(unicon.settings.Settings, 'GRACEFUL_DISCONNECT_WAIT_SEC', 0)
class TestIronWarePluginConnect(unittest.TestCase):
```

2021-01-12 14:14 UTC, dwapstra commented on src/unicon/plugins/tests/test_plugin_ironware.py
> +        self.assertIn(expected_response, ret)
Recommend to change this to self.assertEqual. You will notice that this test will fail unless the right prompt patterns are used to make sure the prompt stripping works.

2021-01-12 14:15 UTC, dwapstra commented on src/unicon/plugins/tests/test_plugin_ironware.py
> +        self.assertIn('mlx8#', c.spawn.match.match_output)
add c.disconnect() to free up resources

2021-01-12 14:15 UTC, dwapstra commented on src/unicon/plugins/tests/test_plugin_ironware.py
> +
add c.disconnect() to free up resources

2021-01-12 14:16 UTC, dwapstra commented on src/unicon/plugins/tests/test_plugin_ironware.py
> +SSH@mlx8#""")
add c.disconnect() to free up resources under 'finally' section.

2021-01-16 12:46 UTC, jamesditrapani commented on src/unicon/plugins/ironware/statemachine.py
> +        super().create()
I presume this will be after a `super()` to `GenericSingleRPStateMachine.create()` still?

2021-01-16 13:04 UTC, jamesditrapani commented on src/unicon/plugins/tests/test_plugin_ironware.py
> +        self.assertIn(expected_response, ret)
@dwapstra What is the difference between `assertEqual` and `assertIn` in this context? Changing this unittest to `assertEqual` causes a failure due. Looks like when using `assertEqual` it picks up on the whole prompt not being stripped, leaving `SSH@`:

```
======================================================================
FAIL: test_execute_show_feature (__main__.TestIronWarePluginExecute)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_plugin_ironware.py", line 108, in test_execute_show_feature
    self.assertEqual(expected_response, ret)
AssertionError: '"Tot[2904 chars].254.251.108  eth 7/1       110/42        O    15h47m -"' != '"Tot[2904 chars].254.251.108  eth 7/1       110/42        O    15h47m -"\nSSH@'
Diff is 3172 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 6 tests in 23.593s

```

2021-01-21 12:09 UTC, jamesditrapani commented on src/unicon/plugins/tests/test_plugin_ironware.py
> +        self.assertIn(expected_response, ret)
@dwapstra Any feedback on the above before I push the latest commit?

2021-01-21 19:08 UTC, jeaubin commented
Hi @jamesditrapani  

we have an upcoming release next Wednesday. If you want to be part of this release, we would need comments to be addressed.

Otherwise, no problem, it can be part of the Feb release (Last Tuesday of every month)

2021-01-21 20:45 UTC, jamesditrapani commented
> Hi @jamesditrapani  
> 
> 
> 
> we have an upcoming release next Wednesday. If you want to be part of this release, we would need comments to be addressed.
> 
> 
> 
> Otherwise, no problem, it can be part of the Feb release (Last Tuesday of every month)

Thanks @jeaubin, just awaiting some feedback from @dwapstra on some of the comments prior to submitting a new commit.

2021-01-28 20:05 UTC, dwapstra commented on src/unicon/plugins/ironware/statemachine.py
> +        super().create()
Correct, my example was not complete.
```python
def create():
        super().create()
```

2021-01-28 20:06 UTC, dwapstra commented on src/unicon/plugins/tests/test_plugin_ironware.py
> +        self.assertIn(expected_response, ret)
The difference is that assertEqual makes sure that the prompt stripping works and we get 'clean' output back. In this case, if the prompt is not stripped, it means the prompt pattern needs an update.

2021-01-28 20:07 UTC, dwapstra commented
@jamesditrapani  replied to your questions. Apologies for the delay.

2021-01-31 01:03 UTC, jamesditrapani commented
> @jamesditrapani replied to your questions. Apologies for the delay.

Requested modifications submitted, thanks.

2021-02-03 13:17 UTC, dwapstra commented on src/unicon/plugins/tests/test_plugin_ironware.py
> +class TestIronWarePluginExecute(unittest.TestCase):
please add 

@patch.object(unicon.settings.Settings, 'POST_DISCONNECT_WAIT_SEC', 0)
@patch.object(unicon.settings.Settings, 'GRACEFUL_DISCONNECT_WAIT_SEC', 0)

2021-02-03 13:17 UTC, dwapstra commented on src/unicon/plugins/tests/test_plugin_ironware.py
> +class TestIronWarePluginMPLSPing(unittest.TestCase):
please add

@patch.object(unicon.settings.Settings, 'POST_DISCONNECT_WAIT_SEC', 0)
@patch.object(unicon.settings.Settings, 'GRACEFUL_DISCONNECT_WAIT_SEC', 0)

2021-02-03 13:18 UTC, dwapstra commented on src/unicon/plugins/ironware/settings.py
> +        self.ESCAPE_CHAR_CALLBACK_PRE_SENDLINE_PAUSE_SEC = 1
does not look like we use this setting anywhere suggest to remove ESCAPE_CHAR_CALLBACK_PRE_SENDLINE_PAUSE_SEC

2021-02-03 13:18 UTC, dwapstra commented
@jamesditrapani  thanks, almost there :)

2021-02-03 13:26 UTC, dwapstra commented
dont forget to resolve the merge conflict..

2021-02-04 10:01 UTC, jamesditrapani commented on src/unicon/plugins/tests/test_plugin_ironware.py
> +class TestIronWarePluginExecute(unittest.TestCase):
Thanks @dwapstra. I cannot find anything in the documentation regarding these (entirely possible I missed it). For my reference, and possibly those in the future, what do these exactly do & why are they needed?

2021-02-04 10:03 UTC, jamesditrapani commented on src/unicon/plugins/ironware/settings.py
> +        self.ESCAPE_CHAR_CALLBACK_PRE_SENDLINE_PAUSE_SEC = 1
@dwapstra Will do. Looks like I accdientally added this line. I believe this is only relevant to Virtual devices.

2021-02-04 10:15 UTC, jamesditrapani commented
> dont forget to resolve the merge conflict..

Cheers. Updates pushed & Merge conflict resolved.

2021-02-06 02:51 UTC, tahigash commented
@dwapstra if looks OK, please approve and merge.

2021-02-09 01:23 UTC, tahigash approved these changes
approved on behalf of Lunzhi

2021-02-11 15:19 UTC, dwapstra approved these changes

2021-02-11 15:19 UTC, merged