updated documentation
CiscoTestAutomation/unicon.plugins pull request #91
Opened 2023-10-16 21:37 UTC by omehrabi

Updated the documentation for the fallback credentials and move the credential part to the the passwords.rst

2023-10-17 15:47 UTC, dwapstra commented on docs/user_guide/passwords.rst
> +For understanding the password handling first we need to understand credentials on pyATS.
```suggestion
Passwords are managed through device credentials in pyATS, the next section explains how credentials are handled in pyATS.
```

2023-10-17 15:53 UTC, dwapstra commented on docs/user_guide/passwords.rst
> +to be raised.
```suggestion
Credentials are not retried, any username or password failure causes a
`UniconAuthenticationError<unicon.core.errors.UniconAuthenticationError>`
to be raised, unless fallback credentials are defined. See :ref:`fallback_credentials`.
```

2023-10-17 15:53 UTC, dwapstra commented on docs/user_guide/passwords.rst
```suggestion

.. _fallback_credentails:

```

2023-10-17 15:53 UTC, dwapstra commented on docs/user_guide/passwords.rst
> +Please see :ref:`credentails` for more details.
```suggestion
Please see :ref:`credentials` for more details.
```

2023-10-17 21:46 UTC, dwapstra commented on docs/user_guide/passwords.rst
> +you could have a default list for all the connections in the testbed:
```suggestion
In case of authentication failure, fallback credentials are used to try and login to the device when they are defined for the connection.  You can define one or more device credentials and define them as fallback credentials by adding them to the fallback credentials list under the `defaults` section or under the connection. The fallback credentials credentials will be used in sequence. If none of the combinations work on the device a bad password exception is raised.

Below an example of a testbed with fallback credentials defined.
```

2023-10-17 21:47 UTC, dwapstra commented on docs/user_guide/passwords.rst
> +or you could define fallback credentails per connection:
```suggestion
Example of fallback credentials per connection:
```

2023-10-17 21:47 UTC, dwapstra requested changes
Please address comments

2023-10-18 21:09 UTC, dwapstra approved these changes

2023-10-24 21:11 UTC, dwapstra commented on docs/user_guide/passwords.rst
> +                - set_2
set_2 is not defined

```suggestion
                - set_1
```

2023-10-24 22:10 UTC, bastell approved these changes

2023-10-24 22:10 UTC, merged